#!/usr/bin/env zsh

export PWD="$( pwd )"
source $PWD/bin/core/utils.zsh

echo "${COLOR_YELLOW}GERONIMOOOOOO ε=ε=ε=ε=┏(;￣▽￣)┛${COLOR_RESET}"

if [[ ! -h "$HOME/.dotfiles" ]]
then
	ln -s $PWD ~/.dotfiles && echo_success "Dotfiles folder linked"
fi
