# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# EXPORTS
export DOTFILES=$HOME/.dotfiles
export SHELL=/bin/zsh
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
export ZSH_CUSTOM=$DOTFILES/zsh-custom
export PATH=/usr/local/bin:/opt/local/bin:/opt/local/sbin:/bin:/usr/sbin:/sbin:/usr/bin
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="$PATH:$DOTFILES/bin/usr"
export EDITOR='vim'
export PATH=$(npm bin):$PATH

# Locales
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"

# nvm
# export NVM_DIR=~/.nvm
#   . $(brew --prefix nvm)/nvm.sh

# Set name of the theme to load.
ZSH_THEME="eramdam"
plugins=(osx battery colored-man copydir copyfile cp sprunge z)
source $ZSH/oh-my-zsh.sh
source $DOTFILES/bin/core/k/k.sh

# Don't spam history w/ "clear"
HIST_IGNORE_SPACE="clear"
DISABLE_AUTO_UPDATE="false"
DISABLE_AUTO_TITLE="true"
COMPLETION_WAITING_DOTS="false"

# ALIASES
alias clock="${DOTFILES}/bin/usr/tty-clock -bsC 4"
alias rezsh='exec $SHELL -l'
alias tmux-cheat="${DOTFILES}/bin/usr/tmux-cheat"
alias origami-cheat="${DOTFILES}/bin/usr/origami-cheat"
alias groot='cd $(git rev-parse --show-cdup)'
alias gp='git push'
alias gpu='git pull'
alias gs='git pull && git push'
alias gh=github
alias add-keys-front="ssh-add -D && ssh-add ~/.ssh/id_rsa"
alias syncFrontSketchFiles="rsync -rv --delete ~/Dropbox\ \(Front\)/DESIGN/{02_OSX-UI,07_WEB} ~/Desktop/Stuff/FrontDesign"
alias gu="gulp"
alias gus="gulp serve"
alias gufs="gulp fast-serve"
alias nf="node front"
alias npif="npm prune && npm i && nf"
alias npibw="npm prune && npm i && gubw"
alias wtf='$(thefuck $(fc -ln -1))'
alias l="k --no-vcs -h"
alias ll="k --no-vcs -ah"
alias lg="k -ah"
alias sort-sizes="du -h --max-depth=1 | sort -h"
alias apm="apm-beta"
alias atom="atom-beta"
alias st='atom'
alias stt='atom .'
alias gtw='gittower .'

alias screenshot-shadow-off='defaults write com.apple.screencapture disable-shadow -bool true'
alias screenshot-shadow-on='defaults write com.apple.screencapture disable-shadow -bool false'

# Servers
alias Trisha="ssh -t Trisha 'tmux a'"
alias FrontStaging="ssh -t FrontStaging"

# Opens a new tmux session w/ a name or re-attach if it exists
function newTmux () {
NAME=$1
tmux a -t $NAME || tmux new -s $NAME
}

function tab-title () {
    echo -ne "\033]0;"$*"\007"
}

function nth-commit() {
  git rev-list HEAD | tail -n $1 | head -n 1
}

ulimit -n 1024
eval "$(rbenv init -)"
# eval "$(tmuxifier init -)"
